import FWCore.ParameterSet.Config as cms
from Configuration.Generator.Pythia8CommonSettings_cfi import *
from Configuration.Generator.Pythia8CUEP8M1Settings_cfi import *

generator = cms.EDFilter("Pythia8GeneratorFilter",
    pythiaPylistVerbosity = cms.untracked.int32(0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    maxEventsToPrint = cms.untracked.int32(0),
    comEnergy = cms.double(13000.0),
    PythiaParameters = cms.PSet(
        pythia8CommonSettingsBlock,
        pythia8CUEP8M1SettingsBlock,
        processParameters = cms.vstring(
             'HardQCD:all = on',
             'PhaseSpace:pTHatMin = 8.',
             '100441:mayDecay = no',
             '100443:mayDecay = no',
             '100553:mayDecay = no',
             '10411:mayDecay = no',
             '10413:mayDecay = no',
             '10421:mayDecay = no',
             '10423:mayDecay = no',
             '10431:mayDecay = no',
             '10433:mayDecay = no',
             '10441:mayDecay = no',
             '10443:mayDecay = no',
             '10511:mayDecay = no',
             '10513:mayDecay = no',
             '10521:mayDecay = no',
             '10523:mayDecay = no',
             '10531:mayDecay = no',
             '10533:mayDecay = no',
             '10541:mayDecay = no',
             '10543:mayDecay = no',
             '10551:mayDecay = no',
             '10553:mayDecay = no',
             '113:mayDecay = no',
             '14122:mayDecay = no',
             '200553:mayDecay = no',
             '20413:mayDecay = no',
             '20423:mayDecay = no',
             '20433:mayDecay = no',
             '20443:mayDecay = no',
             '20513:mayDecay = no',
             '20523:mayDecay = no',
             '20533:mayDecay = no',
             '20543:mayDecay = no',
             '20553:mayDecay = no',
             '221:mayDecay = no',
             '223:mayDecay = no',
             '30443:mayDecay = no',
             '331:mayDecay = no',
             '333:mayDecay = no',
             '4112:mayDecay = no',
             '4114:mayDecay = no',
             '411:mayDecay = no',
             '4122:mayDecay = no',
             '4132:mayDecay = no',
             '413:mayDecay = no',
             '415:mayDecay = no',
             '4212:mayDecay = no',
             '4214:mayDecay = no',
             '421:mayDecay = no',
             '4222:mayDecay = no',
             '4224:mayDecay = no',
             '4232:mayDecay = no',
             '423:mayDecay = no',
             '425:mayDecay = no',
             '4312:mayDecay = no',
             '4314:mayDecay = no',
             '431:mayDecay = no',
             '4322:mayDecay = no',
             '4324:mayDecay = no',
             '4332:mayDecay = no',
             '4334:mayDecay = no',
             '433:mayDecay = no',
             '435:mayDecay = no',
             '4412:mayDecay = no',
             '4414:mayDecay = no',
             '441:mayDecay = no',
             '4422:mayDecay = no',
             '4424:mayDecay = no',
             '4432:mayDecay = no',
             '4434:mayDecay = no',
             '443:mayDecay = no',
             '445:mayDecay = no',
             '5112:mayDecay = no',
             '5114:mayDecay = no',
             '511:mayDecay = no',
             '5122:mayDecay = no',
             '5132:mayDecay = no',
             '513:mayDecay = no',
             '515:mayDecay = no',
             '5212:mayDecay = no',
             '5214:mayDecay = no',
             '521:mayDecay = no',
             '5222:mayDecay = no',
             '5224:mayDecay = no',
             '5232:mayDecay = no',
             '523:mayDecay = no',
             '525:mayDecay = no',
             '5312:mayDecay = no',
             '5314:mayDecay = no',
             '531:mayDecay = no',
             '5322:mayDecay = no',
             '5324:mayDecay = no',
             '5332:mayDecay = no',
             '5334:mayDecay = no',
             '533:mayDecay = no',
             '535:mayDecay = no',
             '541:mayDecay = no',
             '543:mayDecay = no',
             '545:mayDecay = no',
             '551:mayDecay = no',
             '553:mayDecay = no',
             '555:mayDecay = no'
        ),
        parameterSets = cms.vstring('pythia8CommonSettings',
                                    'pythia8CUEP8M1Settings',
                                    'processParameters',
                                    )
    )
)

#filter for b-quark
bfilter = cms.EDFilter("PythiaFilter",
    ParticleID = cms.untracked.int32(5)
)

ProductionFilterSequence = cms.Sequence(generator*bfilter)
